### ISSUE TITLE
Error: Cannot find module 'weak'

### ISSUE THREAD

**Issue by iamnewton** [skratchdot/color-palette#1]
``` bash
#276: $ npm install -g color-palette
-
> phantomjs@1.9.18 install /usr/local/lib/node_modules/color-palette/node_modules/phantomjs
> node install.js

PhantomJS detected, but wrong version 2.0.0 @ /usr/local/bin/phantomjs.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/2b/x43985991b3_t_31n0fc_vq80000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
  [=====================-------------------] 52% 0.0s
Received 9187K total.
Extracting zip contents
Removing /usr/local/lib/node_modules/color-palette/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/2b/x43985991b3_t_31n0fc_vq80000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1442454646117/phantomjs-1.9.8-macosx -> /usr/local/lib/node_modules/color-palette/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /usr/local/lib/node_modules/color-palette/node_modules/phantomjs/lib/phantom/bin/phantomjs

> weak@0.4.1 install /usr/local/lib/node_modules/color-palette/node_modules/phantom/node_modules/dnode/node_modules/weak
> node-gyp rebuild



Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.





Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/color-palette/node_modules/phantom/node_modules/dnode/node_modules/weak
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing weak@0.4.1
/usr/local/bin/color-palette -> /usr/local/lib/node_modules/color-palette/lib/cli.js
color-palette@1.0.3 /usr/local/lib/node_modules/color-palette
├── onecolor@2.5.0
├── mustache@0.8.2
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── phantomjs@1.9.18 (which@1.0.9, progress@1.1.8, kew@0.4.0, request-progress@0.3.1, adm-zip@0.4.4, npmconf@2.1.1, request@2.42.0, fs-extra@0.23.1)
└── phantom@0.7.2 (win-spawn@2.0.0, traverse@0.6.6, shoe@0.0.15, dnode@1.2.1)

#277: $ col
col            colcrt         colldef        color-palette@ colorguard@    colors@        colrm          column

#277: $ color-palette http://google.com
module.js:338
    throw err;
          ^
Error: Cannot find module 'weak'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at new D (/usr/local/lib/node_modules/color-palette/node_modules/phantom/node_modules/dnode/index.js:28:20)
    at module.exports (/usr/local/lib/node_modules/color-palette/node_modules/phantom/node_modules/dnode/index.js:8:12)
    at /usr/local/lib/node_modules/color-palette/node_modules/phantom/phantom.js:159:13
    at Server.handler (/usr/local/lib/node_modules/color-palette/node_modules/phantom/node_modules/shoe/index.js:22:9)
    at Server.emit (events.js:107:17)
    at App.emit (/usr/local/lib/node_modules/color-palette/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/sockjs.js:182:27)
```

**Comment by iamnewton** [comment]
Sometimes it helps to actually read the error message.  When I installed I hadn't agreed to the new license on xCode from the last OS update.

**Comment by skratchdot** [comment]
@chrisopedia - no worries. Thanks for checking out this project!
